### ISSUE TITLE
Dedicated error code for rmdir on non-empty directory

### ISSUE THREAD

**Issue by josephmturner** [RangerMauve/hypercore-fetch#34]
Does the new API makes this possible? https://docs.holepunch.to/building-blocks/hyperdrive#await-drive.del-path

**Comment by RangerMauve** [comment]
Just to clarify, do you want it to throw an error when trying to do a DELETE on an non-empty directory? Currently I think it just lets you delete directories recursively to simplify that use case.

**Comment by josephmturner** [comment]
By "currently", do you mean in hypercore 10?

With hypercore 9 (the current hyper-gateway), attempting to delete a non-empty directory gives a status 500 error.

**Comment by josephmturner** [comment]
If Hypercore 10 lets you recursively delete directories, then I'll probably just add a check in the application to warn users that the directory is not empty.

**Comment by RangerMauve** [comment]
By "currently" I mean hypercore9. I was under the impression that I got recursive directory deletes working, I guess I was wrong there.

Recursive deletes by default is something I'd like to have in the next version. 😅

Being able to do one delete on a dir instead of dozens of requests to do GET/DELETE is nice for UX IMO

**Comment by josephmturner** [comment]
Agreed. Ok, I'm glad recursive deletion will be in the next version!

**Comment by josephmturner** [comment]
Confirmed working in new version!
