### ISSUE TITLE
Possible to have file and dir with same name?

### ISSUE THREAD

**Issue by josephmturner** [RangerMauve/hypercore-fetch#40]
It appears that it's possible to create a file and directory with the same name, only distinguished by a trailing slash. Is this expected?

**Comment by josephmturner** [comment]
Also opened here: https://github.com/holepunchto/hyperdrive-next/issues/29

**Comment by RangerMauve** [comment]
Yeah, this is a function of Hyperdrive and I'd rather defer to their judgement. If they make an update that changes that, we'll combine it here.

Only thing is that technically "folders" don't exist in the new Hyperdrive since it uses prefixes over "entries".

So you might have an entry within a folder name that happens to be the name of another entry.

e.g. with this setup

```
/foo => 'Hello World'
/foo/bar.txt => 'Hello World'
```

`/foo` would be both a folder and a file.
