### ISSUE TITLE
Return list of versions with mtimes at `hyper://PUBLIC-KEY/$/version/`

### ISSUE THREAD

**Issue by josephmturner** [RangerMauve/hypercore-fetch#81]
What do you think about special-casing `hyper://PUBLIC-KEY/$/version/`? First, we should find a standard for sending directory information via JSON first.

**Comment by RangerMauve** [comment]
I don't think an API for this exists in the mean hyperdrive code base.  what's more,  modification times only apply to files and it's very tricky to figure out which file changed without a bunch of extra logic. if you want to perform deaths you should do it at the application level instead of the protocol handlers

**Comment by josephmturner** [comment]
Sounds good!
